# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request_target:
    branches: [ "main" ]

env:
  TURSO_API_TOKEN: ${{ secrets.TURSOCI_TOKEN }}

jobs:

  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  build:
    needs: authorize
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
        #ref: "refs/pull/${{ github.event.number }}/merge" # THIS IS INSECURE

    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v4
      with:
        go-version-file: go.mod

    - name: Format
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

    - name: Install dependencies
      run: go get -v ./...

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet -v ./...

    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.2"
        install-go: false

    - name: Test
      run: go test -v ./...

    - name: Build Turso binary
      run:  go build -o turso cmd/turso/main.go && cp turso cmd/turso

    - name: Integration Test
      run:  go test -v -count=1 -tags=integration ./testing

