name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    permissions:
        id-token: write
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.IKUCTL_GITHUB_TOKEN }}
      - name: Update Turso backoffice
        uses: fjogeleit/http-request-action@v1
        with:
            url: 'https://api.chiseledge.com/releases'
            method: 'POST'
            data: '{ "Version":"$GITHUB_REF_NAME"}'
            bearerToken: ${{ secrets.TURSO_BACKOFFICE_PASSCODE }}
