name: goreleaser

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    permissions:
        id-token: write
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.IKUCTL_GITHUB_TOKEN }}
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo "{ \"Version\":\"$GITHUB_REF_NAME\"}")
        shell: bash
      - name: Echo
        run: echo ${{ steps.get_version.outputs.VERSION }}
      - name: Update Turso backoffice
        uses: fjogeleit/http-request-action@v1
        with:
            url: 'https://api.chiseledge.com/releases'
            method: 'POST'
            data: ${{ steps.get_version.outputs.VERSION }}
            bearerToken: ${{ secrets.TURSOSTAFF_TOKEN }}
